Added script field support
defensestation/osquery pull request #2
Opened 2024-07-21 11:33 UTC by IAbderrahmane

Please note that in the SearchRequest struct we added scriptFields as a concrete type and not an interface unlike Mappable and Aggregation. the thought is it's pretty simple enough that it shouldn't require an interface. 

Can't wait for your feedback!

2024-08-13 19:45 UTC, forderation commented
is there any update? please support this

2024-08-13 19:46 UTC, forderation commented
@tkaur-ds

2024-08-13 19:51 UTC, tkaur-ds commented
Hi, Sorry for delayed response. Its under review currently, will update you soon

2024-08-14 15:34 UTC, tkaur-ds requested changes
Hi @abdoo-Brahimi,

**Thanks for the PR!** We’re almost ready to merge, but I have a small request regarding the `script.go` file.

Currently, you’ve imported the `"github.com/fatih/structs"` package just to use the `Map()` function. While this works, it introduces an additional dependency that might not align with the existing codebase standards.

In the rest of the codebase, similar functionality is achieved without external packages by manually creating the map structure within the `Map()` method. To keep the code consistent and avoid unnecessary imports, could you please modify the `Map()` function in `script.go` to match the pattern used in other files like `terms.go`?

Here’s what I suggest:

Instead of:

```go
func (f *ScriptField) Map() map[string]interface{} {
    return map[string]interface{}{
        "script": structs.Map(f),
    }
}
```

Try something like this:

```go
func (f *ScriptField) Map() map[string]interface{} {
    result := make(map[string]interface{})
    if f.Src != "" {
        result["source"] = f.Src
    }
    if f.Param != nil {
        result["params"] = f.Param
    }
    if f.Id != "" {
        result["id"] = f.Id
    }
    if f.Language != "" {
        result["lang"] = f.Language
    }
    return map[string]interface{}{
        "script": result,
    }
}
```

This way, we maintain consistency across the codebase, and the functionality remains the same.

Let me know if you have any questions or need further clarification!

2024-08-16 09:31 UTC, IAbderrahmane commented
@tkaur-ds I changed it, however I want to ask you about that package, I see it used in the projects, how do you decide when and when not to use it ? since I have other PRs that I want to create

2024-08-16 15:07 UTC, tkaur-ds commented
@IAbderrahmane, Thanks for making the change! The decision to use an external package like `github.com/fatih/structs` typically depends on a few factors: 

1. **Consistency**: We aim to maintain uniformity across the codebase, so we prefer sticking with existing patterns unless there's a strong reason to introduce a new dependency.
2. **Dependencies**: Adding new packages increases maintenance and potential security risks, especially when the package is archived(`github.com/fatih/structs` package is an archive) and no longer maintained.
3. **Project Standards**: If a package is widely used in the project, we might continue using it. Otherwise, we evaluate whether it's necessary or if there's a simpler alternative.

For future PRs, we should continue using the established approach unless there’s a clear benefit to diverging.

2024-08-16 15:08 UTC, tkaur-ds approved these changes

2024-08-16 15:09 UTC, merged